Améliorer états des champs V2
ulaval/modul pull request #233
Opened 2020-02-17 15:06 UTC by raphpare

## Copie du [PR 202](https://github.com/ulaval/modul/pull/202)

## Description
Description du bogue dans ce billet: https://github.com/ulaval/modul/issues/150
Corrige également ce billet: https://github.com/ulaval/modul/issues/80

## Types de changements

- [ ] Correction de bug (sans `breaking change`)
- [ ] Amélioration (ajout par example une nouvelle propriété, évènement, slot ou méthode à un composant existant sans `breaking change`)
- [ ] Nouvelle fonctionalité (nouveau composant, directive, filtre ou service)
- [x] Breaking change (modification à une fonctionnalités existante qui nécessite une migration *remplir la section release note*)
- [ ] Refactoring/ménage (sans `breaking change`)
- [x] Documentation/storybook (changement à la documentation ou aux storybooks qui n'affecte aucun package)
- [ ] Autre

## Comment cela peut-il être testé?

- [ ] Test unitaire (un nouveau test unitaire à été fait)
- [x] Storybook
- [x] Test manuel / Sandboxes
- [ ] Autre

Liste des composant avec une nouvelle storie qui se nomme "state"
- m-textfield
- m-textarea
- m-datepicker
- m-timepiker
- m-dropdown
- m-select
- m-multi-select
- m-typeahead
- m-autocomplete
- m-rich-text-editor
- m-decimalfield
- m-moneyfield

## Inclure cette section dans les release notes

**Changes in the states of the input components**
- Read-only
  - Read-only items can receive focus.
  - Value of readonly items can be copy.
  - Read-only items are part of the navigation sequence with the key.
  - Read-only items have the same visual as deactivated items. However, the value text is not grayed out.
  - Readonly items aren't disabled.
- Waiting
  - Waiting items can receive focus.
  - Value of waiting items can be edit, copy and delete as standard input component.
  - Waiting items are part of the navigation sequence with the key.
  - Waiting items are neither disabled nor read-only by default, but can be disabled if necessary by activating the `disabled` and / or `readonly` porps.

**Component impacted by these modifications**
- m-textfield
- m-textarea
- m-datepicker
- m-timepiker
- m-dropdown
- m-select
- m-multi-select
- m-typeahead
- m-autocomplete
- m-rich-text-editor
- m-decimalfield
- m-moneyfield
## Liens internes
https://github.com/ulaval/modul/issues/150
https://github.com/ulaval/modul/issues/80

2020-02-17 19:01 UTC, chuckmah requested changes
Svp voir pour les regression au niveau du m-phonefield

2020-02-17 19:05 UTC, chuckmah commented
@jipigi @vidal7  

Il faudrait voir les impacts qu'un tel changement peut apporter dans Brio , Avec ce changement les champs waiting=true seront maintenant éditable mais on peut facilement revenir a l'ancien comportement en ajoutant un disabled=true lorsque waiting=true. 

Je le ferai dans 1.1 si possible sinon on peut postponner a 2.0 mais la PR risque de ne pas être mise a jour.

2020-02-18 16:39 UTC, vidal7 commented
> @jipigi @vidal7
> 
> Il faudrait voir les impacts qu'un tel changement peut apporter dans Brio , Avec ce changement les champs waiting=true seront maintenant éditable mais on peut facilement revenir a l'ancien comportement en ajoutant un disabled=true lorsque waiting=true.
> 
> Je le ferai dans 1.1 si possible sinon on peut postponner a 2.0 mais la PR risque de ne pas être mise a jour.

@jipigi, est ce que ce comportement est souhaitable par défaut dans Brio?

2020-02-18 18:00 UTC, vidal7 commented
Je trouve ça lourd comme changement et c'est dur d'évaluer les impacts dans les projets tels que Brio. Je me demande si nous aurions pas pu faire ce changement sans breaking change sous un flag en permettant de faire un "opt-in" pour tester. Là, essentiellement, cela impacte tous les inputs de modUL et à cause de cette complexité, je ne peux pas mesurer l'impact sur Brio ni approuver cette PR.

2020-02-18 19:43 UTC, chuckmah commented
> Je trouve ça lourd comme changement et c'est dur d'évaluer les impacts dans les projets tels que Brio. Je me demande si nous aurions pas pu faire ce changement sans breaking change sous un flag en permettant de faire un "opt-in" pour tester. Là, essentiellement, cela impacte tous les inputs de modUL et à cause de cette complexité, je ne peux pas mesurer l'impact sur Brio ni approuver cette PR.

Merci @vidal7, concernant la stratégie je pensais merger cette PR en develop (avec PR #161 et #229) et ensuite faire une version 1.1.0-beta.1 qui devrait être testé directement dans les projets (brio et AEL). Ensuite après le feedback du QA on pourrait effectuer les changements à savoir si on doit corriger d'autres bugs ou rollbacker complètement la PR. Ensuite quand tout le monde est content je peut faire la release officiel de la 1.1.0

C'est la stratégie la plus simple que je vois (qui est basé pas mal sur ce qui se fait dans un projet open source) qui nous permettrais de faire des évolutions général comme celle décrite dans la PR.

Aussi la demande d'évolution provient de @jipigi, il faudrait voir a quel point cette amélioration est souhaitable et sinon comment on aurait pu la découper autrement

2020-03-20 14:50 UTC, raphpare commented on packages/modul-components/src/components/select/base-select/base-select.html
> +    <slot name="validation-message"></slot>
C'est pour positionner au bon endroit le composant m-validation-message

2020-03-20 17:16 UTC, raphpare commented on packages/modul-components/src/components/select/base-select/base-select.scss
> +    display: inline-flex;
Je viens de régler les ^problème avec phonefield

2020-03-21 19:28 UTC, chuckmah approved these changes

2020-03-21 19:29 UTC, chuckmah commented
@raphpare merci pour les changements, vu l'ampleur des changements nous allons attendre les tests de @jipigi avant de l'inclure dans une version mineur de modul

2021-11-29 19:38 UTC, closed without merging