Bugfix/fix i18n multiselect
ulaval/modul pull request #398
Opened 2020-09-08 15:45 UTC by pobie

## Description

## Types de changements

- [x] Correction de bug (sans `breaking change`)
- [ ] Amélioration (ajout par example une nouvelle propriété, évènement, slot ou méthode à un composant existant sans `breaking change`)
- [ ] Nouvelle fonctionalité (nouveau composant, directive, filtre ou service)
- [ ] Breaking change (modification à une fonctionnalités existante qui nécessite une migration *remplir la section release note*)
- [ ] Refactoring/ménage (sans `breaking change`)
- [ ] Documentation/storybook (changement à la documentation ou aux storybooks qui n'affecte aucun package)
- [ ] Autre

## Comment cela peut-il être testé?

- [ ] Test unitaire (un nouveau test unitaire à été fait)
- [ ] Storybook
- [x] Test manuel / Sandboxes
- [ ] Autre

Je n'ai pas fait de tests unitaires puisqu'il s'agit d'un changement de configuration et le module i18n devrait couvrir les cas d'utilisation dans ses propres tests.

## Inclure cette section dans les release notes

## Liens internes

2020-09-09 14:07 UTC, jpguilmette approved these changes
Ajouter le billet du bug s'il existe

2020-09-09 14:12 UTC, raphpare approved these changes

2020-09-09 14:12 UTC, raphpare commented on src/storybook/src/modul.ts
> +                    formatMode: FormatMode.Vsprintf
@chuckmah , est-ce que nous voulons le formatMode?

2020-09-16 14:48 UTC, chuckmah requested changes

2020-09-16 14:48 UTC, chuckmah commented on src/storybook/src/modul.ts
> +                    formatMode: FormatMode.Vsprintf
Je pense qu'on devrait le laisser par default dans storybook

2020-09-17 15:04 UTC, closed without merging