Given m-message-page it's own state ENUM
ulaval/modul pull request #399
Opened 2020-09-09 12:52 UTC by jfdion

## Description

Les composantes m-message et m-message-page partagent le même ENUM pour la définition de l'état (confirmation, info, warn, error). 

Ce partage d'énum peut entrainer un cycle dans les importations. La solution a donc été de définir un énum d'état pour m-message.

La solution optimale serait d'extraire cet énum d'état et que toutes les composantes le réquérant l'importe (centraliserait les sources de changement et éviterait la répétition).

## Types de changements

- [x] Correction de bug (sans `breaking change`)
- [x] Amélioration (ajout par example une nouvelle propriété, évènement, slot ou méthode à un composant existant sans `breaking change`)
- [ ] Nouvelle fonctionalité (nouveau composant, directive, filtre ou service)
- [ ] Breaking change (modification à une fonctionnalités existante qui nécessite une migration *remplir la section release note*)
- [ ] Refactoring/ménage (sans `breaking change`)
- [ ] Documentation/storybook (changement à la documentation ou aux storybooks qui n'affecte aucun package)
- [ ] Autre

## Comment cela peut-il être testé?

- [ ] Test unitaire (un nouveau test unitaire à été fait)
- [ ] Storybook
- [ ] Test manuel / Sandboxes
- [x] Autre

Le seul test possible est d'avoir un projet créant le cycle de d'import

## Inclure cette section dans les release notes

Creation of an ENUM specific for the configuration of the component `m-message-page` (`MMessagePageState`). The current one (`m-message-state`) can still be used but it might create an import cycle while using `m-dialog` + `m-message` + `m-message-page`

## Liens internes

https://jira.dti.ulaval.ca/browse/ENA2-12611

2020-09-09 17:09 UTC, guignol1981 approved these changes

2020-09-14 11:36 UTC, jomat76 approved these changes

2020-09-16 15:07 UTC, chuckmah requested changes

2020-09-16 15:07 UTC, chuckmah commented on packages/modul-components/src/components/message-page/message-page.ts
>      public state: string;
le type devrait etre MMessagePageState  ?

2020-09-16 15:13 UTC, setur52 approved these changes

2020-09-17 13:21 UTC, jfdion commented on packages/modul-components/src/components/message-page/message-page.ts
>      public state: string;
En théorie, oui, mais est-ce qu'il pourrait y avoir des conflits si quelqu'un utilise l'ancien énum qui était utilisé à cet endroit?

2020-09-17 14:07 UTC, chuckmah commented on packages/modul-components/src/components/message-page/message-page.ts
>      public state: string;
Ça ne devrait pas, compiler en javascript un enum devient une string.. je coirs ?

L'ajout du type va permettre au générateur de produire documentation dans website par le type directement.

2020-09-17 14:14 UTC, jfdion commented on packages/modul-components/src/components/message-page/message-page.ts
>      public state: string;
C'est bon je vais l'ajuster

2020-09-17 16:35 UTC, chuckmah approved these changes

2020-09-17 16:35 UTC, merged