ENA2-12627 - FE ajout de prop titre modal sur photo-editor
ulaval/modul pull request #403
Opened 2020-09-18 18:13 UTC by virginiagallo

## Description

ajout d'une nouvelle propriété titleModal que permettre passer le titre du modal dynamique

## Types de changements

- [ ] Correction de bug (sans `breaking change`)
- [x] Amélioration (ajout par example une nouvelle propriété, évènement, slot ou méthode à un composant existant sans `breaking change`)
- [ ] Nouvelle fonctionalité (nouveau composant, directive, filtre ou service)
- [ ] Breaking change (modification à une fonctionnalités existante qui nécessite une migration *remplir la section release note*)
- [ ] Refactoring/ménage (sans `breaking change`)
- [ ] Documentation/storybook (changement à la documentation ou aux storybooks qui n'affecte aucun package)
- [ ] Autre

## Comment cela peut-il être testé?

- [ ] Test unitaire (un nouveau test unitaire à été fait)
- [x] Storybook
- [ ] Test manuel / Sandboxes
- [ ] Autre

## Inclure cette section dans les release notes

## Liens internes

2020-09-19 16:32 UTC, chuckmah approved these changes

2020-09-20 20:01 UTC, guignol1981 approved these changes

2020-09-21 11:41 UTC, jomat76 requested changes

2020-09-21 11:41 UTC, jomat76 commented on packages/modul-components/src/components/photo-editor/photo-editor.html
> -         :title="i18nTitleModal"
Il faudrait que tu enlèves cette ligne qui n'est plus utile: i18nTitleModal: string = this.$i18n.translate('m-photo-editor:title');

2020-09-21 12:34 UTC, jomat76 approved these changes

2020-09-24 13:24 UTC, merged